"""Regenerate the results tables in README.md from docs/benchmark.json.

    python scripts/update_readme.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NAMES = {
    "naive": "No registration (scanner coordinates)",
    "rigid": "Rigid mutual information",
    "rigid+bspline": "Rigid MI + B-spline (classical)",
    "rigid+voxelmorph": "Rigid MI + **VoxelMorph** (AI)",
    "none": "Registered PET, not enhanced",
    "deconv": "Richardson–Lucy + MRI-guided filter (classical)",
    "vit": "**ViT-hybrid U-Net** (AI, MRI-guided)",
}


def f(v, d=2):
    return "–" if v is None else f"{v:.{d}f}"


def tables(b: dict) -> str:
    reg = b["summary"]["registration"]
    enh = b["summary"]["enhancement"]
    out = [f"*{b['cases']} held-out simulated patients (seeds {b['seeds'][0]}–{b['seeds'][1]}, never seen in "
           f"training), FDG and FET alternating, 2–3 lesions each incl. MRI-occult tumours and radionecrosis. "
           f"CPU only. Generated by `fusionmap benchmark` on {b['date']}.*", "",
           "**Step 1 — alignment error (target registration error over the whole brain)**", "",
           "| Method | Mean TRE (mm) | p95 TRE (mm) | At tumour centres (mm) | Patients with p95 < 2 mm | Time (s) |",
           "|---|---:|---:|---:|---:|---:|"]
    for k in ("naive", "rigid", "rigid+bspline", "rigid+voxelmorph"):
        if k in reg:
            r = reg[k]
            out.append(f"| {NAMES[k]} | {f(r['tre_mean_mm']['mean'])} ± {f(r['tre_mean_mm']['std'])} | "
                       f"{f(r['tre_p95_mm']['mean'])} | {f((r['lesion_tre_mm'] or {}).get('mean'))} | "
                       f"{round(100 * r['cases_under_2mm'])} % | {f(r['seconds']['mean'], 1)} |")
    out += ["", "**Step 2 — PET quality against the ideal (blur-free, noise-free) PET**", "",
            "| Method | PSNR (dB) ↑ | SSIM ↑ | NMAE ↓ | Lesion SUVmax recovery (1 = exact) | Radionecrosis uptake ratio (1 = no hallucination) | Tumours detected | False positives / patient | Time (s) |",
            "|---|---:|---:|---:|---:|---:|---:|---:|---:|"]
    for k in ("none", "deconv", "vit"):
        if k in enh:
            e = enh[k]
            rc = e["lesion_rc"] or {}
            hal = e["hallucination_ratio"] or {}
            out.append(f"| {NAMES[k]} | {f(e['psnr_db']['mean'])} | {f(e['ssim']['mean'], 3)} | {f(e['nmae']['mean'], 4)} | "
                       f"{f(rc.get('mean'))} ± {f(rc.get('std'))} | {f(hal.get('mean'))} | "
                       f"{round(100 * e['sensitivity'])} % | {f(e['false_positives_per_case'])} | {f(e['seconds']['mean'], 1)} |")
    return "\n".join(out)


def main():
    b = json.loads((ROOT / "docs" / "benchmark.json").read_text())
    readme = ROOT / "README.md"
    s = readme.read_text()
    new = "<!-- RESULTS:START -->\n" + tables(b) + "\n<!-- RESULTS:END -->"
    s = re.sub(r"<!-- RESULTS:START -->.*?<!-- RESULTS:END -->", lambda _: new, s, flags=re.S)
    readme.write_text(s)
    print(tables(b))


if __name__ == "__main__":
    main()
